---
- name: Ensure yay build directory exists (as user)
  file:
    path: "/home/{{ arch_user }}/builds"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Clone yay repository (as user)
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: "/home/{{ username }}/builds/yay"
    version: master
    force: yes
    update: yes
  become: false
  run_as: "{{ arch_user }}"

- name: Build and install yay (as user)
  command: makepkg -si --noconfirm
  args:
    chdir: "/home/{{ username }}/builds/yay"
  become: false
  run_as: "{{ username }}"

- name: Sync yay database
  command: yay -Sy
  changed_when: false
  become: true
