- name: Configure Pacman
  import_tasks: pacman.yaml

- name: Install YAY (AUR Helper)
  import_tasks: yay.yaml

- name: Install Packages
  import_tasks: packages.yaml

- name: Clone repositories
  import_tasks: git_clones.yaml

- name: Make use of dotfiles
  import_tasks: dotfiles.yaml

- name: Change default user shell
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh
