- name: Update Yay
  ansible.builtin.shell:
    cmd: yay -Sy
  become: true
  become_user: "{{ username }}"

- name: Install packages
  shell: "yay -S --needed --noconfirm --asexplicit --sudoloop --batchinstall {{ packages | join(' ') }}"
  become: true
  become_user: "{{ username }}"
