- name: Update Yay
  ansible.builtin.shell:
    cmd: yay -Sy
  become: true
  become_user: "{{ username }}"

- name: Install packages
  shell: "yay -S --needed --noconfirm --asexplicit {{ item }}"
  with_items: "{{ packages }}"
  become: true
  become_user: "{{ username }}"
