- name: Update Yay
  ansible.builtin.shell:
    cmd: yay -Sy
  become: true
  become_user: "{{ username }}"

- name: Install packages
  ansible.builtin.shell:
    cmd: "sudo -u {{ username }} yay -S --needed --noconfirm --asexplicit {{ packages | join(' ') }}"
  register: installations
  become: true
  become_user: "{{ username }}"
