username: igorcromai

dotfiles:
  url: https://github.com/igortxra/dotfiles.git

git_clones:
  - name: Zsh Autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions
    depth: 1
    dest: "/home/{{ username }}/.config/zsh/zsh-autosuggestions"
    version: HEAD

  - name: AstroNvim
    repo: https://github.com/igortxra/nvim
    depth: 1
    dest: "/home/{{ username }}/.config/nvim"
    version: HEAD

  - name: PowerLevel10K
    repo: https://github.com/romkatv/powerlevel10k.git
    depth: 1
    dest: "/home/{{ username }}/.config/zsh/powerlevel10k"
    version: HEAD

  - name: asdf-vm
    repo: https://github.com/asdf-vm/asdf.git
    depth: 1
    dest: "/home/{{ username }}/.asdf"
    version: v0.14.1

  - name: Wallpapers
    repo: https://github.com/dracula/wallpaper.git
    depth: 1
    dest: "/home/{{ username }}/Wallpapers/dracula"
    version: HEAD

  - name: Dracula theme for Qutebrowser
    repo: https://github.com/dracula/qutebrowser-dracula-theme.git
    depth: 1
    dest: "/home/{{ username }}/.config/qutebrowser/dracula"
    version: HEAD

packages:
  # Essential
  - vim
  - git

  # Screen Configuration
  - arandr
  - autorandr

  # Wallpapers
  - feh

  # Screenshots
  - flameshot

  # Version Control
  - git
  - github-cli

  # Window Manager
  - qtile

  # Shell
  - zsh

  # Terminal Emulator
  - kitty

  # Launcher
  - rofi
  - dmenu

  # Compositor
  - picom

  # Browser
  - qutebrowser
  - google-chrome # AUR

  # File Manager
  - thunar
  - ranger

  # Notification
  - dunst

  # Themes
  - lxappearance
  - dracula-gtk-theme # AUR
  - dracula-icons-git # AUR
  - dracula-cursors-git # AUR

  # Fonts
  - ttf-iosevka-nerd
  - noto-fonts-cjk
  - noto-fonts-emoji
  - xorg-fonts-100dpi
  - xorg-fonts-75dpi

  # Clipboard
  - xclip
  - rofi-greenclip # AUR

  # Automations
  - ansible
  - ansible-completion-git

  # Utils
  - tldr
  - batify # AUR
  - htop
  - btop
  - fzf
  - less
  - man-db
  - unzip
  - ripgrep
  - archey3
  - numlockx
  - alsa-utils
  - nodejs
  - npm
  - python-dbus-next
  - python-psutil
  - zram-generator

  # Required to run AppImages
  - fuse2

  # Developer Tools
  - docker
  - neovim
  - github-cli
  - asdf-vm # AUR
  - kubectl
  - kind

  # Personal Needs
  - discord
  - spotify-launcher
